### Import

In [1]:
# import numpy
import numpy as np

### Numpy array

In [ ]:
# 넘파이 배열
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)
print(type(array))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [5]:
# 배열의 크기
print(array.shape)

(2, 3)


In [6]:
# 배열의 요소 읽기
print(array[1, 2])
print(array[1][2])

6
6


### 배열의 계산 함수

In [9]:
# 배열의 합
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)
print(array.sum())

[[1 2 3]
 [4 5 6]]
21


In [ ]:
# 배열의 평균
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)
print(array.mean())

[[1 2 3]
 [4 5 6]]
3.5


In [11]:
# 표준편차
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)
print(array.std())

[[1 2 3]
 [4 5 6]]
1.707825127659933
